export const ads = [
    {
        icon: "gibwork.webp",
        title: "gibwork",
        description: "Find Talent, Find Work on Solana",
        url: "https://gib.work/",
        bgColor: "bg-white",
        textColor: "text-black",
        buttonColor: "bg-violet-500",
    },
    {
        icon: "gio.avif",
        title: "drip.haus/gio",
        description: "15.4k followers on drip house",
        url: "https://drip.haus/gio",
        bgColor: "bg-slate-900",
        textColor: "text-amber-300",
        buttonColor: "bg-red-600",
    },
    {
        icon: "buu.jpg",
        title: "BUU",
        description: "Little tricks, big trouble",
        url: "https://buu.monster",
        bgColor: "bg-cyan-950",
        textColor: "text-yellow-400",
        buttonColor: "bg-black",
    },
    {
        icon: "dolos.jpg",
        title: "DOLOS",
        description: "Ancient Villain Reborn",
        url: "https://x.com/dolos_diary",
        bgColor: "bg-dolos-500",
        textColor: "text-dolos-900",
        buttonColor: "bg-dolos-900",
    },
];