[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
memeoor = "memev6gnPZhMteK2mQ2GXpHv6ZNtCFJsbzbhG3A3T1m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
# url = "https://api.devnet.solana.com"
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# [[test.validator.account]]
# address = "harkLSUe2Puud2TVQUhHW4vs45mF1YMLU3PThPCuWd8"
# filename = "~/.config/solana/id.json"
