[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
poa = "attn9Nw2iXDoW2guYwdtmh4xagadhhXqYcnbHTyfK5r"

[programs.devnet]
poa = "attn9Nw2iXDoW2guYwdtmh4xagadhhXqYcnbHTyfK5r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
# url = "https://api.devnet.solana.com"
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# [[test.genesis]] 
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
# program = "target/deploy/mpl_token_metadata.so"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# [[test.validator.account]]
# address = "harkLSUe2Puud2TVQUhHW4vs45mF1YMLU3PThPCuWd8"
# filename = "~/.config/solana/id.json"
